[package]
name = "cert-exporter-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
der-parser = "*"
thiserror = "1"
x509-parser = "0.10"
chrono = "0.4.19"
glob = "0.3.0"
prometheus_exporter = "0.8.2"
